### ISSUE TITLE
Hide out of stock items

### ISSUE THREAD

**Issue by hans2103** [SolsWebdesign/Sols_Upsells#5]
at this moment it is not possible to hide the out of stock items from the collection of upsell items. 
De Magento System -> Configuration -> Catalog -> Inventory -> Stock Options -> Display Out of Stock Products is set to Yes and has to stay as is. 
Using Amasty Custom Stock Status is used to display the current stock status of the main product.

For the products in the upsell list I want to hide the out of stock items.
how can this be done?

**Comment by SolsWebdesign** [comment]
This one is a bit complicated because of the configurable product: you have to check the stock of every simple to decide if you want to show the (complete) configurable. And then even if you find that for instance a simple with color green and size 8 is out of stock, it will still display the attributes (green and size 8) because of the setting System -> Configuration -> Catalog -> Inventory -> Stock Options -> Display Out of Stock Products set to Yes...
But if the whole product is out-of-stock then you could do this:
`<?php foreach ($this->getItemCollection()->getItems() as $_link): ?>
        <?php $stockItem = $_link->getStockItem(); ?>
        <?php if($stockItem->getIsInStock()) : ?>`
somewhere around line 34 after the "foreach [...] as $_link"you check the stock for the whole product and if it is in stock, you show it. Don't forget to add the `<?php endif; ?>` just before the `<?php endforeach; ?>` at the end.

**Comment by hans2103** [comment]
very complicated indeed... Once an entire product is out of stock the suggested solution is helpful. 
But that's not the always the case. 
For instance the green t-shirt. Only size 8 is out of stock.... Sizes 6, 7 and 9 are in stock. 
Therefor only these options should be shown.... or size 8 should have a custom stock status. 
(side note: https://amasty.com/custom-stock-status.html does not work on related products nor upsell products yet)
